esphome:
  name: xtoys-mqtt
  friendly_name: xtoys-mqtt

esp8266:
  board: esp01_1m

# Enable logging
logger:

ota:
  password: "<<some-ota-password>>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: <<MQTT server>>
  username: <<MQTT user>>
  password: <<MQTT password>>
  discovery: false
  will_message: 
  log_topic: null

sensor:
  - platform: mqtt_subscribe
    name: "data"
    id: data
    topic: xtoys/fm
    internal: True
    on_value:
      then:
        - light.turn_on:
            id: out
            brightness: !lambda "return ( id(data).state / 100.0);"
           

# Example configuration entry
output:
  - platform: esp8266_pwm
    pin: 5
    frequency: 10
    id: pwm_output


light:
  - platform: monochromatic
    internal: True
    output: pwm_output
    name: "PWM out"
    id: out
    default_transition_length: 0s


number:
  - platform: template
    id: frequency
    name: "Frequency"
    min_value: 1
    max_value: 100
    step: 1
    optimistic: True
    initial_value: 40
    on_value:
      then:
         - output.esp8266_pwm.set_frequency:
            id: pwm_output
            frequency: !lambda "return id(frequency).state;"
  - platform: template
    id: percent
    name: "Percent"
    min_value: 0
    max_value: 100
    step: 1
    optimistic: True
    initial_value: 0
    on_value:
      then:
        - light.turn_on:
            id: out
            brightness: !lambda "return ( id(percent).state / 100.0);"

web_server:
  local: true
  port: 80
  ota: false
  
